# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interview.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_interview(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(313, 394)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(121, 40, 81, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(120, 110, 81, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(130, 180, 72, 15))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(130, 250, 72, 15))
        self.label_4.setObjectName("label_4")
        self.textBrowser = QtWidgets.QTextEdit(Form)
        self.textBrowser.setGeometry(QtCore.QRect(20, 70, 271, 31))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextEdit(Form)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 140, 271, 31))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QComboBox(Form)
        self.textBrowser_3.setGeometry(QtCore.QRect(20, 210, 271, 31))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_3.addItem("")
        self.textBrowser_3.addItem("")
        self.textBrowser_3.addItem("")
        self.textBrowser_3.addItem("")
        self.textBrowser_3.addItem("")
        self.textBrowser_3.addItem("")
        self.textBrowser_4 = QtWidgets.QTextEdit(Form)
        self.textBrowser_4.setGeometry(QtCore.QRect(20, 280, 271, 31))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(30, 340, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 340, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "面试信息录入"))
        self.label.setText(_translate("Form", "录用人学号"))
        self.label_2.setText(_translate("Form", "录用人姓名"))
        self.label_3.setText(_translate("Form", "录用人岗位"))
        self.textBrowser_3.setItemText(0, _translate("Form", "技术岗"))
        self.textBrowser_3.setItemText(1, _translate("Form", "运营岗"))
        self.textBrowser_3.setItemText(2, _translate("Form", "设计岗"))
        self.textBrowser_3.setItemText(3, _translate("Form", "产品岗"))
        self.textBrowser_3.setItemText(4, _translate("Form", "市场/销售岗"))
        self.textBrowser_3.setItemText(5, _translate("Form", "职能岗"))
        self.label_4.setText(_translate("Form", "录用薪资"))
        self.pushButton.setText(_translate("Form", "确定"))
        self.pushButton_2.setText(_translate("Form", "返回"))
