# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'job_fair_s.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_job_fair_s(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(605, 629)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 10, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(310, 10, 72, 15))
        self.label_2.setObjectName("label_2")
        self.textBrowser_12 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_12.setGeometry(QtCore.QRect(30, 33, 261, 45))
        self.textBrowser_12.setObjectName("textBrowser_12")
        self.textBrowser_13 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_13.setGeometry(QtCore.QRect(310, 33, 261, 45))
        self.textBrowser_13.setObjectName("textBrowser_13")
        self.textBrowser_14 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_14.setGeometry(QtCore.QRect(30, 180, 541, 351))
        self.textBrowser_14.setObjectName("textBrowser_14")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 160, 72, 15))
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(380, 540, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(110, 580, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(380, 580, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(110, 540, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.textBrowser_15 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_15.setGeometry(QtCore.QRect(310, 110, 261, 31))
        self.textBrowser_15.setObjectName("textBrowser_15")
        self.textBrowser_16 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_16.setGeometry(QtCore.QRect(30, 110, 261, 31))
        self.textBrowser_16.setObjectName("textBrowser_16")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 80, 81, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(310, 80, 111, 16))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "招聘会信息"))
        self.label.setText(_translate("Form", "招聘会"))
        self.label_2.setText(_translate("Form", "企业"))
        self.label_3.setText(_translate("Form", "岗位信息"))
        self.pushButton_3.setText(_translate("Form", "返回"))
        self.pushButton_4.setText(_translate("Form", "上一条"))
        self.pushButton_2.setText(_translate("Form", "下一条"))
        self.pushButton.setText(_translate("Form", "报名参会"))
        self.label_4.setText(_translate("Form", "招聘会编号"))
        self.label_5.setText(_translate("Form", "企业社会信用号"))
