# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'job_fair.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_job_fair(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(605, 480)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 20, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(300, 20, 72, 15))
        self.label_2.setObjectName("label_2")
        self.textBrowser_12 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_12.setGeometry(QtCore.QRect(30, 43, 261, 45))
        self.textBrowser_12.setObjectName("textBrowser_12")
        self.textBrowser_13 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_13.setGeometry(QtCore.QRect(310, 43, 261, 45))
        self.textBrowser_13.setObjectName("textBrowser_13")
        self.textBrowser_14 = QtWidgets.QTextBrowser(Form)
        self.textBrowser_14.setGeometry(QtCore.QRect(30, 120, 541, 281))
        self.textBrowser_14.setObjectName("textBrowser_14")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 90, 72, 15))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(100, 430, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 430, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(440, 430, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "招聘会信息"))
        self.label.setText(_translate("Form", "招聘会"))
        self.label_2.setText(_translate("Form", "企业"))
        self.label_3.setText(_translate("Form", "岗位信息"))
        self.pushButton.setText(_translate("Form", "上一条"))
        self.pushButton_2.setText(_translate("Form", "下一条"))
        self.pushButton_3.setText(_translate("Form", "返回"))
